### PR TITLE
Pop up modal

### PR DESCRIPTION
**Pull request by whitzhu**
1. Added modal section under cards. 
2. Adjusted text field CSS so when it's infocus the background is transparent. 
3. Moved 'form' section under 'button' section

### CODE REVIEW

**Comment by 66eli77** [comment]
awesome work!

**Comment by 66eli77** [comment]
only one thing @whitzhu , the modal does not pop up ; )

**Comment by whitzhu** [comment]
@66eli77 

For the modal not popping out, are you referring to animation or the style? 

Animation Wise:
where should the modal pop out from?
Should I place a button so when people press it, the modal pops out?

Style Wise:
Add shadows? lols jk

**Comment by 66eli77** [comment]
@whitzhu  no shadows please, but you can add an dark semitransparent layer underneath the modal. 
here's any example :  http://www.w3schools.com/bootstrap/bootstrap_modal.asp

**Pull request merged**
